<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!</h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
<div style="clear:both;"></div>

<form action="http://wuno.com/nick/invoice/public/invoice" method="POST" target="frame" id="printInvoice" name="printInvoice" class="form-horizontal" role="form">
  <div class="form-group">
    <label class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="yourName" id="yourName" type="text" placeholder="Your Name">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
      <input class="form-control" name="address" id="address" type="text" placeholder="Address">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Hourly Rate</label>
    <div class="col-sm-10">
      <input class="form-control calc" name="rate" id="rate" type="text" placeholder="Hourly Rate">
    </div>
  </div>

<div class="form-group">
    <label class="col-sm-2 control-label">Customer's Name</label>
    <div class="col-sm-10">
      <input class="form-control" name="customerName" id="customerName" type="text" placeholder="Customer's Name">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Customer's Phone</label>
    <div class="col-sm-10">
      <input class="form-control" name="customerPhone" id="customerPhone" type="text" placeholder="Customer's Phone">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Date Job Completed</label>
    <div class="col-sm-10">
      <input class="form-control" name="djc" id="djc" type="text" placeholder="Date Job Completed">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Hours Worked</label>
    <div class="col-sm-10">
      <input class="form-control calc" name="hours" id="hours" type="text" placeholder="Hours Worked">
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Description of Work</label>
    <div class="col-sm-10">
      <input class="form-control" name="description" id="description" type="text" placeholder="Description of Work">
    </div>
  </div>

    <div class="form-group">
    <label class="col-sm-2 control-label">Total Cost</label>
    <div class="col-sm-10">
      <input class="form-control total" name="total" id="total" type="text" placeholder="Total Cost">
    </div>
  </div>

    <div class="form-group">
    <label class="col-sm-2 control-label">Comments</label>
    <div class="col-sm-10">
      <textarea class="form-control" name="comments" id="comments" rows="5" placeholder="Comments or Job Description"></textarea> 
    </div>
  </div>

      <div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-10">
      <button type="submit" id="exec" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>

<script>
// Calculates the hours and rate ten injets it to the #total field
jQuery(function(){
$('#rate').val(0);
$('#hours').val(0);
$('#total').val(0);
    $(".calc").focusout(function() {
      rate = parseFloat($("#rate").val());
      hours = parseFloat($("#hours").val());
      total = rate * hours;
      $('#total').val(total);
    }); 
});
</script>


