<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Hourly Work Invoice'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('This project was made to illustrate my skill set as a programmer. Going into this project I had no experience with Zend2. I was able to complete this project within 3 nights which involved a lot of reading, coffee and broken keyboards. Thank you for this opportunity. I hope you enjoy analyzing my program as much as I did making it.'), '<a href="https://www.wuno.com/" target="_blank">', '</a>') ?></p>
    <p><a class="btn wunoBtn btn-lg" href="https://www.wuno.com/" target="_blank"><?php echo $this->translate('Check Out My Website | wunO.com') ?> &raquo;</a></p>
</div>


